/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Create DSS App Token": {                        "en": "Create DSS App Token",                            "de": "DSS-App-Token erstellen",                         "ru": "Создать токен приложения DSS",                    "pt": "Criar token de aplicativo DSS",                   "nl": "Maak een DSS-app-token",                          "fr": "Créer un jeton d'application DSS",                "it": "Crea token app DSS",                              "es": "Crear token de aplicación DSS",                   "pl": "Utwórz token aplikacji DSS",                      "zh-cn": "创建DSS应用令牌"},
    "DSS App-Token": {                               "en": "DSS App-Token",                                   "de": "DSS App-Token",                                   "ru": "DSS App-Token",                                   "pt": "DSS token do aplicativo",                         "nl": "DSS app-token",                                   "fr": "Jeton d'application DSS",                         "it": "Token app DSS",                                   "es": "Token de aplicación DSS",                         "pl": "Token aplikacji DSS",                             "zh-cn": "DSS应用令牌"},
    "DSS Host": {                                    "en": "DSS Host",                                        "de": "DSS-Host",                                        "ru": "DSS Host",                                        "pt": "Host DSS",                                        "nl": "DSS-host",                                        "fr": "Hôte DSS",                                        "it": "Host DSS",                                        "es": "DSS Host",                                        "pl": "Host DSS",                                        "zh-cn": "DSS主机"},
    "DSS Password": {                                "en": "DSS Password",                                    "de": "DSS-Passwort",                                    "ru": "Пароль DSS",                                      "pt": "Senha do DSS",                                    "nl": "DSS-wachtwoord",                                  "fr": "Mot de passe DSS",                                "it": "Password DSS",                                    "es": "Contraseña DSS",                                  "pl": "Hasło DSS",                                       "zh-cn": "DSS密码"},
    "DSS Username": {                                "en": "DSS Username",                                    "de": "DSS-Benutzername",                                "ru": "Имя пользователя DSS",                            "pt": "Nome de usuário do DSS",                          "nl": "DSS-gebruikersnaam",                              "fr": "Nom d'utilisateur DSS",                           "it": "Nome utente DSS",                                 "es": "Nombre de usuario DSS",                           "pl": "Nazwa użytkownika DSS",                           "zh-cn": "DSS用户名"},
    "Data Polling Interval": {                       "en": "Data polling Interval",                           "de": "Datenabfrageintervall",                           "ru": "Интервал опроса данных",                          "pt": "Intervalo de sondagem de dados",                  "nl": "Data Polling-interval",                           "fr": "Intervalle d'interrogation des données",          "it": "Intervallo di polling dei dati",                  "es": "Intervalo de sondeo de datos",                    "pl": "Interwał sondowania danych",                      "zh-cn": "数据轮询间隔"},
    "Error while retrieving DSS App-Token": {        "en": "Error happened while retrieving DSS App-Token",   "de": "Fehler beim Abrufen des DSS-App-Token",           "ru": "Ошибка при получении токена приложения DSS",      "pt": "Erro ao recuperar o DSS token",                   "nl": "Fout bij het ophalen van DSS App-Token",          "fr": "Erreur lors de la récupération du jeton d'application DSS", "it": "Errore durante il recupero del token app DSS",    "es": "Error al recuperar DSS App-Token",                "pl": "Błąd podczas pobierania tokenu aplikacji DSS",    "zh-cn": "检索DSS应用令牌时出错"},
    "I have App token": {                            "en": "I already have an App token",                     "de": "Ich habe bereits einen App-Token",                "ru": "У меня уже есть токен приложения",                "pt": "Eu já tenho um token de aplicativo",              "nl": "Ik heb een app-token",                            "fr": "J'ai un jeton d'application",                     "it": "Ho un token app",                                 "es": "Tengo token de aplicación",                       "pl": "Mam token aplikacji",                             "zh-cn": "我有应用令牌"},
    "I have no App token": {                         "en": "I don't have an App token",                       "de": "Ich habe noch keinen App-Token",                  "ru": "У меня нет токена приложения",                    "pt": "Ainda não tenho um token de aplicativo",          "nl": "Ik heb geen app-token",                           "fr": "Je n'ai pas de jeton d'application",              "it": "Non ho un token app",                             "es": "No tengo token de aplicación",                    "pl": "Nie mam tokena aplikacji",                        "zh-cn": "我没有应用令牌"},
    "Provide Login data to automatically retrieve a DSS App-Token": {"en": "Provide DSS Login data to automatically retrieve a DSS App-Token", "de": "DSS-Anmeldedaten eingeben, um automatisch einen DSS-App-Token abzurufen", "ru": "Укажите данные для входа в систему для автоматического получения токена приложения DSS", "pt": "Insira as credenciais do DSS para obter automaticamente um token do aplicativo DSS", "nl": "Verstrek inloggegevens om automatisch een DSS app-token op te halen", "fr": "Fournir des données de connexion pour récupérer automatiquement un jeton d'application DSS", "it": "Fornire i dati di accesso per recuperare automaticamente un token app DSS", "es": "Proporcione datos de inicio de sesión para recuperar automáticamente un token de aplicación DSS", "pl": "Podaj dane logowania, aby automatycznie pobrać token aplikacji DSS", "zh-cn": "提供登录数据以自动检索DSS应用令牌"},
    "Request Device Output values actively": {       "en": "Actively request Device Output values",           "de": "Ausgabewerte der Geräte aktiv abfragen",          "ru": "Активно запрашивать выходные данные устройства",  "pt": "Consultar ativamente os valores de saída dos dispositivos", "nl": "Verzoek Device Output-waarden actief",            "fr": "Demander activement les valeurs de sortie de périphérique", "it": "Richiedere attivamente i valori di output del dispositivo", "es": "Solicitar valores de salida del dispositivo activamente", "pl": "Aktywnie żądaj wartości wyjściowych urządzenia",  "zh-cn": "主动请求设备输出值"},
    "Successfully retrieved DSS App-Token": {        "en": "Successfully retrieved DSS App-Token",            "de": "DSS-App-Token erfolgreich abgerufen",             "ru": "Успешно получен токен приложения DSS",            "pt": "Token de aplicativo DSS obtido com sucesso",      "nl": "DSS app-token opgehaald",                         "fr": "Jeton d'application DSS récupéré avec succès",    "it": "Token app DSS recuperati correttamente",          "es": "Token de aplicación DSS recuperado con éxito",    "pl": "Pomyślnie odzyskano token aplikacji DSS",         "zh-cn": "成功检索DSS应用令牌"},
    "Use Scene Preset Values": {                     "en": "Use Scene Preset Values",                         "de": "Szenen-Voreinstellungswerte verwenden",           "ru": "Использовать предустановленные значения сцены",   "pt": "Use os valores predefinidos da cena",             "nl": "Gebruik vooraf ingestelde scènewaarden",          "fr": "Utiliser les valeurs prédéfinies de scène",       "it": "Usa valori preimpostati scena",                   "es": "Usar valores preestablecidos de escena",          "pl": "Użyj wstępnie ustawionych wartości scen",         "zh-cn": "使用场景预设值"},
    "You have to start the adapter before you can retrieve the DSS App-Token": {"en": "You have to start the instance before you can retrieve the DSS App-Token", "de": "Die Instanz muss gestartet sein, bevor das DSS-App-Token abgerufen werden kann", "ru": "Вы должны запустить адаптер, прежде чем сможете получить токен приложения DSS.", "pt": "A instância deve ser iniciada antes que o token de aplicativo DSS possa ser obtido", "nl": "U moet de adapter starten voordat u het DSS App-Token kunt ophalen", "fr": "Vous devez démarrer l'adaptateur avant de pouvoir récupérer le jeton d'application DSS", "it": "È necessario avviare l'adattatore prima di poter recuperare il token app DSS", "es": "Debe iniciar el adaptador antes de poder recuperar el token de aplicación DSS", "pl": "Aby móc pobrać token aplikacji DSS, musisz uruchomić adapter", "zh-cn": "您必须先启动适配器，然后才能检索DSS App-Token"},
    "digitalstrom adapter settings": {               "en": "Digitalstrom Instance Settings",                  "de": "Digitalstrom Instanzeinstellungen",               "ru": "Настройки адаптера для digitalstrom",             "pt": "Configurações do adaptador para Digitalstrom",    "nl": "Adapterinstellingen voor digitalstrom",           "fr": "Paramètres d'adaptateur pour digitalstrom",       "it": "Impostazioni dell'adattatore per digitalstrom",   "es": "Ajustes del adaptador para digitalstrom",         "pl": "Ustawienia adaptera dla digitalstrom",            "zh-cn": "digitalstrom的适配器设置"},
};