/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'digitalstrom adapter settings': {
        'en': 'Adapter settings for digitalstrom',
        'de': 'Adaptereinstellungen für digitalstrom',
        'ru': 'Настройки адаптера для digitalstrom',
        'pt': 'Configurações do adaptador para digitalstrom',
        'nl': 'Adapterinstellingen voor digitalstrom',
        'fr': "Paramètres d'adaptateur pour digitalstrom",
        'it': "Impostazioni dell'adattatore per digitalstrom",
        'es': 'Ajustes del adaptador para digitalstrom',
        'pl': 'Ustawienia adaptera dla digitalstrom',
        'zh-cn': 'digitalstrom的适配器设置'
    },
    "DSS Host": {
        "en": "DSS Host",
        "de": "DSS-Host",
        "ru": "DSS Host",
        "pt": "Host DSS",
        "nl": "DSS-host",
        "fr": "Hôte DSS",
        "it": "Host DSS",
        "es": "DSS Host",
        "pl": "Host DSS",
        "zh-cn": "DSS主机"
    },
    "DSS App-Token": {
        "en": "DSS App-Token",
        "de": "DSS App-Token",
        "ru": "DSS App-Token",
        "pt": "DSS App-Token",
        "nl": "DSS app-token",
        "fr": "Jeton d'application DSS",
        "it": "Token app DSS",
        "es": "Token de aplicación DSS",
        "pl": "Token aplikacji DSS",
        "zh-cn": "DSS应用令牌"
    },
    "Provide Login data to automatically retrieve a DSS App-Token": {
        "en": "Provide Login data to automatically retrieve a DSS App-Token",
        "de": "Geben Sie Anmeldedaten ein, um ein DSS-App-Token automatisch abzurufen",
        "ru": "Укажите данные для входа в систему для автоматического получения токена приложения DSS.",
        "pt": "Forneça dados de login para recuperar automaticamente um DSS App-Token",
        "nl": "Verstrek inloggegevens om automatisch een DSS app-token op te halen",
        "fr": "Fournir des données de connexion pour récupérer automatiquement un jeton d'application DSS",
        "it": "Fornire i dati di accesso per recuperare automaticamente un token app DSS",
        "es": "Proporcione datos de inicio de sesión para recuperar automáticamente un token de aplicación DSS",
        "pl": "Podaj dane logowania, aby automatycznie pobrać token aplikacji DSS",
        "zh-cn": "提供登录数据以自动检索DSS应用令牌"
    },
    "DSS Username": {
        "en": "DSS Username",
        "de": "DSS-Benutzername",
        "ru": "Имя пользователя DSS",
        "pt": "Nome de usuário DSS",
        "nl": "DSS-gebruikersnaam",
        "fr": "Nom d'utilisateur DSS",
        "it": "Nome utente DSS",
        "es": "Nombre de usuario DSS",
        "pl": "Nazwa użytkownika DSS",
        "zh-cn": "DSS用户名"
    },
    "DSS Password": {
        "en": "DSS Password",
        "de": "DSS-Passwort",
        "ru": "Пароль DSS",
        "pt": "Senha DSS",
        "nl": "DSS-wachtwoord",
        "fr": "Mot de passe DSS",
        "it": "Password DSS",
        "es": "Contraseña DSS",
        "pl": "Hasło DSS",
        "zh-cn": "DSS密码"
    },
    "Create DSS App Token": {
        "en": "Create DSS App Token",
        "de": "DSS-App-Token erstellen",
        "ru": "Создать токен приложения DSS",
        "pt": "Criar token de aplicativo DSS",
        "nl": "Maak een DSS-app-token",
        "fr": "Créer un jeton d'application DSS",
        "it": "Crea token app DSS",
        "es": "Crear token de aplicación DSS",
        "pl": "Utwórz token aplikacji DSS",
        "zh-cn": "创建DSS应用令牌"
    },
    "Data Polling Interval": {
        "en": "Data Polling Interval",
        "de": "Datenabrufintervall",
        "ru": "Интервал опроса данных",
        "pt": "Intervalo de pesquisa de dados",
        "nl": "Data Polling-interval",
        "fr": "Intervalle d'interrogation des données",
        "it": "Intervallo di polling dei dati",
        "es": "Intervalo de sondeo de datos",
        "pl": "Interwał sondowania danych",
        "zh-cn": "数据轮询间隔"
    },
    "You have to start the adapter before you can retrieve the DSS App-Token": {
        "en": "You have to start the adapter before you can retrieve the DSS App-Token",
        "de": "Sie müssen den Adapter starten, bevor Sie das DSS-App-Token abrufen können",
        "ru": "Вы должны запустить адаптер, прежде чем сможете получить токен приложения DSS.",
        "pt": "É necessário iniciar o adaptador antes de recuperar o DSS App-Token",
        "nl": "U moet de adapter starten voordat u het DSS App-Token kunt ophalen",
        "fr": "Vous devez démarrer l'adaptateur avant de pouvoir récupérer le jeton d'application DSS",
        "it": "È necessario avviare l'adattatore prima di poter recuperare il token app DSS",
        "es": "Debe iniciar el adaptador antes de poder recuperar el token de aplicación DSS",
        "pl": "Aby móc pobrać token aplikacji DSS, musisz uruchomić adapter",
        "zh-cn": "您必须先启动适配器，然后才能检索DSS App-Token"
    },
    "Error while retrieving DSS App-Token": {
        "en": "Error while retrieving DSS App-Token",
        "de": "Fehler beim Abrufen des DSS-App-Token",
        "ru": "Ошибка при получении токена приложения DSS",
        "pt": "Erro ao recuperar o DSS App-Token",
        "nl": "Fout bij het ophalen van DSS App-Token",
        "fr": "Erreur lors de la récupération du jeton d'application DSS",
        "it": "Errore durante il recupero del token app DSS",
        "es": "Error al recuperar DSS App-Token",
        "pl": "Błąd podczas pobierania tokenu aplikacji DSS",
        "zh-cn": "检索DSS应用令牌时出错"
    },
    "Successfully retrieved DSS App-Token": {
        "en": "Successfully retrieved DSS App-Token",
        "de": "DSS-App-Token erfolgreich abgerufen",
        "ru": "Успешно получен токен приложения DSS",
        "pt": "DSS App-Token recuperado com sucesso",
        "nl": "DSS app-token opgehaald",
        "fr": "Jeton d'application DSS récupéré avec succès",
        "it": "Token app DSS recuperati correttamente",
        "es": "Token de aplicación DSS recuperado con éxito",
        "pl": "Pomyślnie odzyskano token aplikacji DSS",
        "zh-cn": "成功检索DSS应用令牌"
    },
    "Use Scene Preset Values": {
        "en": "Use Scene Preset Values",
        "de": "Verwenden Sie Szenenvoreinstellungswerte",
        "ru": "Использовать предустановленные значения сцены",
        "pt": "Usar valores predefinidos de cena",
        "nl": "Gebruik vooraf ingestelde scènewaarden",
        "fr": "Utiliser les valeurs prédéfinies de scène",
        "it": "Usa valori preimpostati scena",
        "es": "Usar valores preestablecidos de escena",
        "pl": "Użyj wstępnie ustawionych wartości scen",
        "zh-cn": "使用场景预设值"
    },
    "I have no App token": {
        "en": "I have no App token",
        "de": "Ich habe kein App-Token",
        "ru": "У меня нет приложения токен",
        "pt": "Não tenho token de aplicativo",
        "nl": "Ik heb geen app-token",
        "fr": "Je n'ai pas de jeton d'application",
        "it": "Non ho un token app",
        "es": "No tengo token de aplicación",
        "pl": "Nie mam tokena aplikacji",
        "zh-cn": "我没有应用令牌"
    },
    "I have App token": {
        "en": "I have App token",
        "de": "Ich habe ein App-Token",
        "ru": "У меня есть токен приложения",
        "pt": "Eu tenho token de aplicativo",
        "nl": "Ik heb een app-token",
        "fr": "J'ai un jeton d'application",
        "it": "Ho un token app",
        "es": "Tengo token de aplicación",
        "pl": "Mam token aplikacji",
        "zh-cn": "我有应用令牌"
    },
    "Request Device Output values actively": {
        "en": "Request Device Output values actively",
        "de": "Geräteausgangswerte aktiv abfragen",
        "ru": "Активно запрашивать выходные данные устройства",
        "pt": "Solicitar valores de saída do dispositivo ativamente",
        "nl": "Verzoek Device Output-waarden actief",
        "fr": "Demander activement les valeurs de sortie de périphérique",
        "it": "Richiedere attivamente i valori di output del dispositivo",
        "es": "Solicitar valores de salida del dispositivo activamente",
        "pl": "Aktywnie żądaj wartości wyjściowych urządzenia",
        "zh-cn": "主动请求设备输出值"
    }
};